# -*- coding: utf-8 -*-
"""line_graph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WO5cVzzANbVXeH5taOmQQW_4aMEwYNdO
"""

import matplotlib.pyplot as plt

traditional_normal = 0.97   # accuracy on normal (unmasked)
traditional_masked = 0.5   # accuracy on masked faces
fusion_normal = 0.98       # accuracy on normal (unmasked)
fusion_masked = 0.78        # accuracy on masked faces

x_labels = ["Normal Faces", "Masked Faces"]
x = [0, 1]

plt.figure(figsize=(7,5))
plt.plot(x, [traditional_normal*100, traditional_masked*100], marker='o', label="Traditional CNN", linewidth=2.5, color='red')
plt.plot(x, [fusion_normal*100, fusion_masked*100], marker='o', label="Quadrant-FusionNet", linewidth=2.5, color='blue')
plt.xticks(x, x_labels, fontsize=12)
plt.yticks(range(0, 101, 10))
plt.xlabel("Dataset Type", fontsize=13)
plt.ylabel("Recognition Accuracy (%)", fontsize=13)
plt.title("Model Performance Comparison on Masked vs Normal Faces", fontsize=14)
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()



import matplotlib.pyplot as plt
import numpy as np

# ----------------------------------------------------------
# Replace these with your actual accuracies from experiments
# ----------------------------------------------------------
# Traditional baseline model
traditional_normal = 0.97     # accuracy on normal faces
traditional_masked = 0.05     # accuracy on masked faces

# Our proposed Quadrant-Fusion (local + global)
fusion_normal = 0.98          # accuracy on normal faces
fusion_masked = 0.78          # accuracy on masked faces

# ----------------------------------------------------------
# Prepare data for plotting
# ----------------------------------------------------------
x_labels = ["Normal Faces", "Masked Faces"]
x = np.arange(len(x_labels))

traditional_acc = [traditional_normal * 100, traditional_masked * 100]
fusion_acc = [fusion_normal * 100, fusion_masked * 100]

# ----------------------------------------------------------
# Plot
# ----------------------------------------------------------
plt.figure(figsize=(8,6))
plt.plot(x, traditional_acc, marker='o', color='red', linewidth=3, label="Traditional CNN")
plt.plot(x, fusion_acc, marker='o', color='blue', linewidth=3, label="Local + Global (Ours)")

# Styling
plt.xticks(x, x_labels, fontsize=12)
plt.yticks(range(0, 101, 10))
plt.xlabel("Dataset Type", fontsize=13)
plt.ylabel("Recognition Accuracy (%)", fontsize=13)
plt.title("Performance Comparison: Traditional vs Local + Global (Ours)", fontsize=14)
plt.legend(fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)

# Annotate accuracy values
for i in range(len(x)):
    plt.text(x[i]-0.1, traditional_acc[i]+1, f"{traditional_acc[i]:.1f}%", color='red', fontsize=11)
    plt.text(x[i]+0.05, fusion_acc[i]+1, f"{fusion_acc[i]:.1f}%", color='blue', fontsize=11)

plt.show()